Rails.application.routes.draw do
  get 'jobs/homes'
  get 'jobs/top'
  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/edit'
  get 'user/top'
  get 'user/about'
  get 'user/index'
  get 'user/show'
  get 'user/edit'
  get 'book/index'
  get 'book/show'
  get 'book/edit'
  get 'book/top'
  get 'book/about'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
